export enum MenuType {
  VIANDES = 'VIANDES',
  SANDWICHS = 'SANDWICHS',
  SALADES = 'SALADES',
  POUTINES = 'POUTINES',
  PORCHERIES = 'PORCHERIES',
  POISSONS = 'POISSONS',
  PIZZASTHICK = 'PIZZASTHICK',
  PIZZASTHIN = 'PIZZASTHIN',
  ENTREESSHARED = 'ENTREESSHARED',
  ENTREES = 'ENTREES',
  BURGERS = 'BURGERS',
  BABY = 'BABY',
}
